### ISSUE TITLE
Hoe voeg ik mijn project toe?

### ISSUE THREAD

**Issue by Zae** [vrijplaatsleiden/voordekunst-projects#1]
Hoi,

Ik was benieuwd hoe ik mijn project kan toevoegen aan de plugin, ik zie nergens een optie om de url van mijn voordekunst pagina toe te voegen.

**Comment by fpieters** [comment]
We zijn nog bezig met het gladstrijken van onduidelijkheden en het schrijven van documentatie.
Maar leuk dat je er al mee aan de slag wil! 

Om deze wordpress plugin te gebruiken moet je eerst d.m.v [de crawler](https://github.com/vrijplaatsleiden/voordekunst-crawler) alle data ophalen.
Er is een [cli_example.php](https://github.com/vrijplaatsleiden/voordekunst-crawler/blob/master/src/cli_example.php) waar je de koppeling met de database en je project aanmaakt.
Na het draaien van de crawler kan de wordpress plugin geinstalleerd worden en is er in de widget aan te geven welk project.

Maar we zijn dus nog bezig om alles te verduidelijken en mogelijk zelfs alles samen te voegen tot een simpeler formaat.

**Comment by row-b** [comment]
Ik heb zojuist documentatie toegevoegd voor het WordPress plugin gedeelte. Documentatie voor de Crawler volgt zsm.

**Comment by Zae** [comment]
Ah, de crawler had ik gemist, dank!
